// Generated by ecs compiler version 1.0.1
// Please include this file after your component definitions.
// Please set C++ standard 17 for your compiler.

#include <cstdint>
#include <vector>
#include <list>
#include <unordered_map>

namespace ecs {
#if defined(DEBUG) || defined(Debug) || defined(ECS_DEBUG) || defined(ecs_debug)
#include <cassert>
#include <cstdio>
  #define ecs_debug_assert(x)       assert(x)
  #define ecs_debug_print(fmt, ...) fprintf(stdout, "[ecs_debug] " fmt, ##__VA_ARGS__);
  #define ecs_fatal(fmt, ...)       fprintf(stdout, "[ecs_fatal] " fmt, ##__VA_ARGS__);ecs_debug_assert(0);
#else
  #define ecs_debug_assert(x)       ((void)(x))
  #define ecs_debug_print(fmt, ...)
  #define ecs_fatal(fmt, ...)
#endif

#define ToUintptr(ptr)          reinterpret_cast<uintptr_t>(ptr)
#define ToPositionPtr(ptr)      reinterpret_cast<Position*>(ptr)
#define ToHealthPointPtr(ptr)   reinterpret_cast<HealthPoint*>(ptr)

//----------------------------------------------------------------+
//  Public interface for serializing all entities and components. |
//----------------------------------------------------------------+
// +------------------------------Entity Table----------------------------------+
// |                                                                            |
// | |<--The Entity-->|<---------The Entity's Component Array---------------->| |
// |                                                                            |
// | +---entity[0]----+-- slot[0]---+---slot[1]--+---slot[2]--+---slot[...n]--+ |
// | | id + version   | componentA  | componentB | componentC | component...  | |
// | +----------------+-------------+------------+------------+---------------+ |
// | +---entity[1]----+-- slot[0]---+---slot[1]--+---slot[2]--+---slot[...n]--+ |
// | | id + version   | componentA  | componentB | componentC | component...  | |
// | +----------------+-------------+------------+------------+---------------+ |
// | +---entity[2]----+-- slot[0]---+---slot[1]--+---slot[2]--+---slot[...n]--+ |
// | | id + version   | componentA  | componentB | componentC | component...  | |
// | +----------------+-------------+------------+------------+---------------+ |
// | +---entity[...]--+-- slot[0]---+---slot[1]--+---slot[2]--+---slot[...n]--+ |
// | | id + version   | componentA  | componentB | componentC | component...  | |
// | +----------------+-------------+------------+------------+---------------+ |
// +----------------------------------------------------------------------------+
class EntityTableVisitor{
public:
  EntityTableVisitor() = default;
  virtual ~EntityTableVisitor() = default;

  virtual void visitEntityTableBegin(){};
  virtual void visitEntityBegin(uint32_t entityId) = 0;

  virtual void visitComponent(const Position& position) = 0;
  virtual void visitComponent(const HealthPoint& healthPoint) = 0;

  virtual void visitEntityEnd(uint32_t entityId) = 0;
  virtual void visitEntityTableEnd(){};
};

//-----------------------+
// Component infomation. |
//-----------------------+
namespace ComponentId{
  constexpr uint32_t Position = 0;
  constexpr uint32_t HealthPoint = 1;
  constexpr uint32_t SIZE = 2; // The number of component ids.
};

template<typename T>
struct ComponentInfo{
  static constexpr uint32_t id = ComponentId::SIZE;
  using type = T;
};

template<>
struct ComponentInfo<Position>{
  static constexpr uint32_t id = ComponentId::Position;
  using type = Position;
};

template<>
struct ComponentInfo<HealthPoint>{
  static constexpr uint32_t id = ComponentId::HealthPoint;
  using type = HealthPoint;
};

//---------------------+
// ecs implementation. |
//---------------------+

// The entity.
struct entity_t {
  uint32_t id;      // entity id.
  uint32_t version; // entity version.
  entity_t(uint32_t i = 0, uint32_t ver = 0) : id{i}, version{ver}{}
  bool operator == (const entity_t& other)const { return this->id == other.id && this->version == other.version; }
  bool operator != (const entity_t& other)const { return this->id != other.id || this->version != other.version; }
};

// The entity's component array.
struct ComponentArray {
  entity_t e;                         // The component array's owner.
  uintptr_t slots[ComponentId::SIZE]; // Each slot is a pointer to a component,

  ComponentArray() :e{}, slots{}{}
  ~ComponentArray(){ clearSlots(); }
  ComponentArray(const ComponentArray& other) = delete;       // You must deep copy the component array.
  ComponentArray& operator=(const ComponentArray&) = delete;  // You must deep copy the component array.

  // Check whether the entity has all the components.
  template<typename... Args>
  bool has() { return (hasComponentImpl<Args>() && ...); }

  // Get a component.
  template<typename T>
  T* get(){
    static_assert(ComponentInfo<T>::id < ComponentId::SIZE, "The component type is not registered!");
    using ComponentType = typename ComponentInfo<T>::type;
    return reinterpret_cast<ComponentType*>(slots[ComponentInfo<T>::id]);
  }

  // Clone slots(deep copy).
  ComponentArray* clone(){
    ComponentArray* cloned = new ComponentArray{};
    if(slots[0]) cloned->slots[0] = ToUintptr(new Position{*ToPositionPtr(slots[0])});
    if(slots[1]) cloned->slots[1] = ToUintptr(new HealthPoint{*ToHealthPointPtr(slots[1])});
    return cloned;
  }

  // Visit slots.
  void visit(EntityTableVisitor* visitor){
    if(slots[0]) visitor->visitComponent(*ToPositionPtr(slots[0]));
    if(slots[1]) visitor->visitComponent(*ToHealthPointPtr(slots[1]));
  }

  // Clear slots.
  void clearSlots(){
    if(slots[0]){ delete ToPositionPtr(slots[0]); slots[0] = 0; }
    if(slots[1]){ delete ToHealthPointPtr(slots[1]); slots[1] = 0; }
  }

private:
  template<typename T>
  bool hasComponentImpl(){
    static_assert(ComponentInfo<T>::id < ComponentId::SIZE, "The component type is not registered!");
    return slots[ComponentInfo<T>::id] != 0;
  }
};

using EntityTable = std::vector<ComponentArray*>;

// pool_t to manage all component buffer.
class pool_t {
private:
  EntityTable mEntityTable;   // The entity table.
  size_t mCurrentTableSize;   // Current entity table size.
  size_t mNextTableId;        // Next avaiable table id.
  std::unordered_map<uint32_t, size_t> mEntityIdToTableId;  // [entity id] to [table id].
  std::list<uint32_t> mRecycledEntityIds;                   // Used to store expired entity ids.
  uint32_t mNextEntityId;                                   // Used to generate new entity id.

  // Store expired entity id.
  inline void storeExpiredEntityId(uint32_t entityId){ mRecycledEntityIds.push_back(entityId); }

  // Create new entity id.
  inline uint32_t getNextEntityId(){
    if (!mRecycledEntityIds.empty()) {
      uint32_t recycledId = mRecycledEntityIds.front();
      mRecycledEntityIds.erase(mRecycledEntityIds.begin());
      return recycledId;
    }
    return mNextEntityId++;
  }

public:
  pool_t() :mEntityTable{new ComponentArray{}}, mCurrentTableSize(1), mNextTableId(1), mNextEntityId(1) {
    // table index 0 is reserved for empty entity.
  }
  ~pool_t() { for (auto& componentArray : mEntityTable){  delete componentArray; } }

  // Create new entity.
  entity_t createEntity(){
    uint32_t entityId = getNextEntityId();
    uint32_t versionId = 1;
    auto& tableId = mEntityIdToTableId[entityId];
    if(tableId == 0) tableId = mNextTableId++;     // Try to use expired component buffer.

    ComponentArray* componentArray;                // Create entity's component array.
    if(tableId < mCurrentTableSize){               // Use expired component buffer.
      componentArray = mEntityTable[tableId];      // Occupy the expired component buffer.
      if(componentArray->e.version < UINT32_MAX){  // Increase expired component version id.
        versionId = componentArray->e.version + 1; // Update version id.
      }
    }else{                                        // Expanding the table.
      componentArray = new ComponentArray{};      // Create new component buffer.
      mEntityTable.push_back(componentArray);     // Manage the new component buffer.
      ++mCurrentTableSize;                        // Update the table size.
    }

    componentArray->e.id = entityId;        // Update entity id.
    componentArray->e.version = versionId;  // Update version id.
    return componentArray->e;               // Return new entity.
  }

  // Check whether the entity exists or is valid, return entity table id.
  size_t hasEntity(const entity_t& entity) const {
    if (auto search = mEntityIdToTableId.find(entity.id); search != mEntityIdToTableId.end()){
      auto pComponentArray = mEntityTable[search->second];
      if(pComponentArray->e == entity){
        return search->second;
      }
    }
    return 0;
  }

  // Destroy an entity.
  void destroyEntity(const entity_t& entity){
    if (auto search = mEntityIdToTableId.find(entity.id); search != mEntityIdToTableId.end()){
      auto pComponentArray = mEntityTable[search->second];
      if(pComponentArray->e == entity){
        pComponentArray->clearSlots();
        // Increase pComponentArray->e.version to make entity invalid. 
        if(entity.version < UINT32_MAX){
          pComponentArray->e.version = entity.version + 1;
        }else{
          pComponentArray->e.version = 1;
        }
        // Swap this component array buffer at the table end so it can be reused.
        std::swap(mEntityTable[search->second], mEntityTable[--mNextTableId]);
        // store expired entity id so it can be reused.
        storeExpiredEntityId(entity.id);
        return;
      }else{
        ecs_fatal("[%s][%d]: invalid entity.\n", __func__, __LINE__);
      }
    }
    ecs_fatal("[%s][%d]: the entity doesn't exist.\n", __func__, __LINE__);
  }

  // Add a component for an entity.
  template <typename T, typename... Args>
  T& addComponent(const entity_t& entity, Args&&... args) {
    static_assert(ComponentInfo<T>::id < ComponentId::SIZE, "The component type is not registered!");
    if (auto search = mEntityIdToTableId.find(entity.id); search != mEntityIdToTableId.end()){
      auto pComponentArray = mEntityTable[search->second];
      if(pComponentArray->e == entity){
        if(pComponentArray->slots[ComponentInfo<T>::id] == 0){
          auto comp = new T{std::forward<Args>(args)...};
          pComponentArray->slots[ComponentInfo<T>::id] = ToUintptr(comp);
          return *comp;
        }else{
          ecs_fatal("[%s][%d]: cannot add the same component more than once.\n", __func__, __LINE__);
        }
      }else{
        ecs_fatal("[%s][%d]: invalid entity.\n", __func__, __LINE__);
      }
    }
    ecs_fatal("[%s][%d]: the entity doesn't exist.\n", __func__, __LINE__);
    return *(reinterpret_cast<T*>(mEntityTable[0]->slots[ComponentInfo<T>::id]));
  }

  // Add a component(if the component doesn't exist) or update the component(if it exists).
  template <typename T, typename... Args>
  T& patchComponent(const entity_t& entity, Args&&... args) {
    static_assert(ComponentInfo<T>::id < ComponentId::SIZE, "The component type is not registered!");
    if (auto search = mEntityIdToTableId.find(entity.id); search != mEntityIdToTableId.end()){
      auto pComponentArray = mEntityTable[search->second];
      if(pComponentArray->e == entity){
        if(pComponentArray->slots[ComponentInfo<T>::id] != 0){
          delete reinterpret_cast<T*>(pComponentArray->slots[ComponentInfo<T>::id]);
        }
        auto comp = new T{std::forward<Args>(args)...};
        pComponentArray->slots[ComponentInfo<T>::id] = ToUintptr(comp);
        return *comp;
      }else{
        ecs_fatal("[%s][%d]: invalid entity.\n", __func__, __LINE__);
      }
    }
    ecs_fatal("[%s][%d]: the entity doesn't exist.\n", __func__, __LINE__);
    return *(reinterpret_cast<T*>(mEntityTable[0]->slots[ComponentInfo<T>::id]));
  }

  // Check whether the entity has the component.
  template <typename T>
  bool hasComponent(const entity_t& entity) const{
    static_assert(ComponentInfo<T>::id < ComponentId::SIZE, "The component type is not registered!");
    if (auto search = mEntityIdToTableId.find(entity.id); search != mEntityIdToTableId.end()){
      auto pComponentArray = mEntityTable[search->second];
      if(pComponentArray->e == entity){
        return pComponentArray->slots[ComponentInfo<T>::id] != 0;
      }
    }
    return false;
  }

  // Check whether the table index has the component.
  template <typename T>
  bool hasComponentFastCheck(const size_t& tableId) const{
    static_assert(ComponentInfo<T>::id < ComponentId::SIZE, "The component type is not registered!");
    return mEntityTable[tableId]->slots[ComponentInfo<T>::id] != 0;
  }

  // Erase a component for the entity.
  template <typename T>
  void eraseComponent(const entity_t& entity){
    static_assert(ComponentInfo<T>::id < ComponentId::SIZE, "The component type is not registered!");
    if (auto search = mEntityIdToTableId.find(entity.id); search != mEntityIdToTableId.end()){
      auto pComponentArray = mEntityTable[search->second];
      if(pComponentArray->e == entity){
        if(pComponentArray->slots[ComponentInfo<T>::id]){
          delete reinterpret_cast<T*>(pComponentArray->slots[ComponentInfo<T>::id]);
          pComponentArray->slots[ComponentInfo<T>::id] = 0;
          return;
        }
      }
    }
    ecs_debug_print("[%s][%d]: shouldn't goto here\n", __func__, __LINE__);
  }

  // Get a component from the entity.
  template <typename T>
  T& getComponent(const entity_t& entity)const{
    static_assert(ComponentInfo<T>::id < ComponentId::SIZE, "The component type is not registered!");
    if (auto search = mEntityIdToTableId.find(entity.id); search != mEntityIdToTableId.end()){
      auto pComponentArray = mEntityTable[search->second];
      if(pComponentArray->e == entity){
        ecs_debug_assert(pComponentArray->slots[ComponentInfo<T>::id]);
        return *(reinterpret_cast<T*>(pComponentArray->slots[ComponentInfo<T>::id]));
      }else{
        ecs_fatal("[%s][%d]: invalid entity.\n", __func__, __LINE__);
      }
    }
    ecs_fatal("[%s][%d]: the entity doesn't exist.\n", __func__, __LINE__);
    return *(reinterpret_cast<T*>(mEntityTable[0]->slots[ComponentInfo<T>::id]));
  }

  // Get the entity's component array.
  ComponentArray& getComponentArray(const entity_t& entity)const{
    if (auto search = mEntityIdToTableId.find(entity.id); search != mEntityIdToTableId.end()){
      auto pComponentArray = mEntityTable[search->second];
      if(pComponentArray->e == entity){
        return *pComponentArray;
      }else{
        ecs_fatal("[%s][%d]: invalid entity.\n", __func__, __LINE__);
      }
    }
    ecs_fatal("[%s][%d]: the entity doesn't exist.\n", __func__, __LINE__);
    return *mEntityTable[0];
  }

  // Set new component array for the entity.
  ComponentArray& setComponentArray(const entity_t& entity, ComponentArray* newComponentArray){
    if (auto search = mEntityIdToTableId.find(entity.id); search != mEntityIdToTableId.end()){
      auto& pComponentArray = mEntityTable[search->second];
      if(pComponentArray->e == entity){
        if(newComponentArray){
          delete pComponentArray;
          pComponentArray = newComponentArray;
          pComponentArray->e = entity; // make sure the owner is valid.
        }else{
          ecs_fatal("[%s][%d]: newComponentArray cannot be nullptr.\n", __func__, __LINE__);
        }
        return *pComponentArray;
      }else{
        ecs_fatal("[%s][%d]: invalid entity.\n", __func__, __LINE__);
      }
    }else{
      ecs_fatal("[%s][%d]: the entity doesn't exist.\n", __func__, __LINE__);
    }
    return *mEntityTable[0];
  }

  // Visit all entities.
  void visit(EntityTableVisitor* visitor){
    if(visitor == nullptr) return;
    visitor->visitEntityTableBegin();
    size_t size = getEntityTableSize();
    for(size_t i = 1; i < size; ++i){ // (i=0) is reserved for null entity.
      visitor->visitEntityBegin(mEntityTable[i]->e.id);
      mEntityTable[i]->visit(visitor);
      visitor->visitEntityEnd(mEntityTable[i]->e.id);
    }
    visitor->visitEntityTableEnd();
  }

  // Get entity table.
  EntityTable* getEntityTable(){ return &mEntityTable; }

  // get entity table size.
  size_t getEntityTableSize()const{ return std::min<size_t>(mNextTableId, mCurrentTableSize); }

  // Clear all the entities.
  void clear(){ 
    for (auto& componentArray : mEntityTable){  delete componentArray; }
    mEntityTable.clear(); 
    mEntityTable.emplace_back(new ComponentArray{});
    mCurrentTableSize = 1;
    mNextTableId = 1;
    mNextEntityId = 1;
    mEntityIdToTableId.clear();
    mRecycledEntityIds.clear();
  }
}; // end pool_t

// registry_t provide public entity apis.
class registry_t {
private:
  pool_t pool;

public:
  registry_t() = default;
  registry_t(const registry_t&) = delete;
  registry_t& operator=(const registry_t&) = delete;

  // Create an entity.
  entity_t create() { return pool.createEntity(); }

  // Destroy an entity.
  void destroy(const entity_t& e) { pool.destroyEntity(e); }

  // Check whether the entity exists or valid.
  bool isValid(const entity_t& e) const { return (bool)(pool.hasEntity(e)); }

  // Add a component for an entity.
  template <typename T, typename... Args>
  T& emplace(const entity_t& e, Args&&... args) {
    return pool.addComponent<T>(e, std::forward<Args>(args)...);
  }

  // Add a component(if the component doesn't exist) or update the component(if it exists).
  template <typename T, typename... Args>
  T& patch(const entity_t& e, Args&&... args) {
    return pool.patchComponent<T>(e, std::forward<Args>(args)...);
  }

  // Get a component from the entity.
  template <typename T>
  T& get(const entity_t& e) { return pool.getComponent<T>(e); }

  // Erase a component for an entity.
  template <typename T>
  void erase(const entity_t& e) { pool.eraseComponent<T>(e); }

  // Check whether the entity has the component.
  template<typename T>
  bool has(const entity_t& e)const { return pool.hasComponent<T>(e); }

  // Check whether the entity has all the components.
  template<typename... Args>
  bool has(const entity_t& e) {
    auto tableId = pool.hasEntity(e);
    return (pool.hasComponentFastCheck<Args>(tableId) && ...);
  }

  // Get an entity's component array.
  ComponentArray& getComponentArray(const entity_t& e)const{ 
    return pool.getComponentArray(e); 
  }

  // Set an entity's component array.
  ComponentArray& setComponentArray(const entity_t& e, ComponentArray* newComponentArray){
    return pool.setComponentArray(e, newComponentArray);
  }

  // Visit all entities.
  void visit(EntityTableVisitor* visitor){ if(visitor) pool.visit(visitor); }

  // Entity iterator.
  class EntityIterator{
  public:
    EntityIterator(EntityTable* table = nullptr, size_t i = 0):table_(table), i_(i){}
    EntityIterator& operator++() { ++i_; return *this;}
    EntityIterator& operator--() { if(i_ > 0) --i_;return *this; }
    EntityIterator operator++(int) { EntityIterator tmp = *this; ++i_; return tmp; }
    EntityIterator operator--(int) { EntityIterator tmp = *this; if(i_ > 0) --i_; return tmp; }
    bool operator==(const EntityIterator& other)const { return this->i_ == other.i_; };
    bool operator!=(const EntityIterator& other)const { return this->i_ != other.i_; };
    bool operator <(const EntityIterator& other)const { return this->i_ < other.i_; };
    const entity_t& operator*()const { return (*table_)[i_]->e; }
    const entity_t* operator->()const { return &((*table_)[i_]->e); }
  private:
    EntityTable* table_;
    size_t i_;
  };

  // Entity iterator begin.
  EntityIterator begin(){ return EntityIterator{pool.getEntityTable(), 1}; }

  // Entity iterator end.
  EntityIterator end(){ return EntityIterator{pool.getEntityTable(), pool.getEntityTableSize()}; }

  // Clear all the entities.
  void clear(){ pool.clear(); }
}; // end class registry_t

} // end namespace ecs

