#pragma once

// Generated by cmake config.
namespace config{
constexpr const char* ECS_COMIPLER_NAME = "ecs";
constexpr const char* ECS_COMIPLER_VERSION = "1.0.1";
constexpr const int MAX_NUMBER_OF_COMPONENTS = 64;
}
